// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDrD_UbGwSP-JsCyGok-nQT19uouo_zY3c',
    appId: '1:866801983108:web:636c0ebda649a04cf02cd1',
    messagingSenderId: '866801983108',
    projectId: 'energeye-54685',
    authDomain: 'energeye-54685.firebaseapp.com',
    storageBucket: 'energeye-54685.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAqxRJuJlvwRQ1KlaTkpnyvjtN9pYHJnbY',
    appId: '1:866801983108:android:7682bbb6a00f465bf02cd1',
    messagingSenderId: '866801983108',
    projectId: 'energeye-54685',
    storageBucket: 'energeye-54685.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAHD9LgSRhcBvdIOXF9JzaYraG5Re4MpjQ',
    appId: '1:866801983108:ios:a295a914e2ff0108f02cd1',
    messagingSenderId: '866801983108',
    projectId: 'energeye-54685',
    storageBucket: 'energeye-54685.firebasestorage.app',
    iosBundleId: 'com.example.miniproject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAHD9LgSRhcBvdIOXF9JzaYraG5Re4MpjQ',
    appId: '1:866801983108:ios:a295a914e2ff0108f02cd1',
    messagingSenderId: '866801983108',
    projectId: 'energeye-54685',
    storageBucket: 'energeye-54685.firebasestorage.app',
    iosBundleId: 'com.example.miniproject',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDrD_UbGwSP-JsCyGok-nQT19uouo_zY3c',
    appId: '1:866801983108:web:bdd5bcdd11094844f02cd1',
    messagingSenderId: '866801983108',
    projectId: 'energeye-54685',
    authDomain: 'energeye-54685.firebaseapp.com',
    storageBucket: 'energeye-54685.firebasestorage.app',
  );
}
